### ISSUE TITLE
hitting the back button on a user page results in JSON showing up instead of HTML

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#44]

**Comment by williamcodes** [comment]
Is this a browser plugin issue? Try reproducing incognito.

**Comment by ramillim** [comment]
I've seen this also. According to some Stackoverflow threads, it's because the last cached response gets returned when you hit the back button, so in the case of the users page, that's the JSON of the readings data used to generate the chart.

Some suggestions are explained here: http://stackoverflow.com/questions/10715852/json-breaking-back-button-in-chrome-reload-button-in-ie-showing-as-naked-data
