### ISSUE TITLE
download the heat log as a csv

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#48]
As a user,
When I go to my tenant page,
And I click on the "Download as CSV" button,
Then I get a CSV file,
And that file has columns for time, indoor temp, outdoor temp, violation status, and sensor ID

**Comment by oliverbarnes** [comment]
`As a tenant`, perhaps? ;)

**Comment by williamcodes** [comment]
Hmm, this is tricky because both tenants and advocates can get to this page. I haven't seen syntax like `As a tenant or an advocate` before, but maybe that's fine?

**Comment by oliverbarnes** [comment]
I think it's fine, a lot more informative than `user`, because we associate to their motives. Which would be good to have as well, actually. It could be something like

```
In order to share my reading history with others
As a tenant or an advocate
I want to download a CSV file from my tenant page
```

Also avoiding declaring actual interface interactions like clicking on buttons with specific names. Interactions and implementation details can be asserted within the tests themselves, perhaps unit tests.

This is a good post going over the advantages of this declarative (as opposed to imperative) style:

http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html

**Comment by williamcodes** [comment]
Good suggestion. I like that better. Closing this issue and opening a new one with your language.
